=== aoarashi1988/majsoul-plus-client/src/resourcepack/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "resourcepack",
  "description": "MajsoulPlus Resource Pack describe file schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[_a-zA-Z0-9]+$"
    },
    "version": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "author": {
      "type": ["string", "array"],
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "preview": {
      "type": "string"
    },
    "dependencies": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "string"
        }
      }
    },
    "replace": {
      "type": "array",
      "items": {
        "oneOf": [
          { "type": "string" },
          {
            "type": "object",
            "properties": {
              "from": {
                "oneOf": [
                  { "type": "string" },
                  {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                ]
              },
              "to": {
                "type": "string"
              },
              "all-servers": {
                "type": "boolean"
              },
              "replace": {
                "type": "boolean"
              }
            }
          }
        ]
      }
    }
  },
  "required": ["id", "version"]
}

=== aoarashi1988/majsoul-plus-client/resourcepack/mallard/resourcepack.json
{
  "id": "mallard",
  "version": "1.0.0",
  "name": "千织普通改绿头鸭",
  "author": "Handle",
  "description": "图片来源pixabay，由Capri23auto上传，CC0协议\n这是一个Mod示范，用途为将普通千织立绘和头像改为绿头鸭。",
  "preview": "preview.jpg",

  "dependencies": {
    "majsoul_plus": "^2.0.0"
  },
  "replace": [
    {
      "from": [
        "audio/sound/qianzhi/lobby_normal1.mp3",
        "audio/sound/qianzhi/lobby_normal2.mp3",
        "audio/sound/qianzhi/lobby_normal3.mp3",
        "audio/sound/qianzhi/lobby_normal4.mp3",
        "audio/sound/qianzhi/lobby_normal5.mp3"
      ],
      "to": "audio/quack.mp3"
    },
    "extendRes/charactor/qianzhi/bighead.png",
    "extendRes/charactor/qianzhi/full.png",
    "extendRes/charactor/qianzhi/half.png",
    "extendRes/charactor/qianzhi/smallhead.png",
    "extendRes/charactor/qianzhi/waitingroom.png"
  ]
}
